### ISSUE TITLE
app can crash on initial load due to Grid configuration

### ISSUE THREAD

**Issue by hagoptaminian** [graasp/graasp-app-thermal-radiation#18]
specifically, the `<Grid />` component calculates `totalNumberOfYTicks = gridHeight - LATTICE_HEIGHT...` and uses that number to create a `new Array(totalNumberOfYTicks)`. at app initialization, `gridHeight` is 0 so `totalNumberOfYTicks` is negative, crashing the `new Array()` call

**Comment by pyphilia** [comment]
closed in #17
